name: deploy-release
on:
  push:
    tags:
      - '*.*.*'
  
env:
  GODOT_VERSION: 3.4.4
jobs:
  export-and-release:
    name: Export and Release
    runs-on: ubuntu-20.04
    container:
      image: barichello/godot-ci:3.4.4
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          lfs: true
      - name: Setup
        run: |
          mkdir -v -p ~/.local/share/godot/templates
          mv /root/.local/share/godot/templates/${GODOT_VERSION}.stable ~/.local/share/godot/templates/${GODOT_VERSION}.stable
      - name: Windows Build
        run: |
          mkdir -v -p Deploy/Windows
          godot -v --export "Windows Desktop" Deploy/Windows/OldImageFilterTool.exe
      - name: Mac Build
        run: |
          mkdir -v -p Deploy/Mac
          godot -v --export "Mac OSX" Deploy/Mac/OldImageFilterTool.zip
      - name: Upload Windows Artifact
        uses: actions/upload-artifact@v1
        with:
          name: OldImageFilterToolWindows$GITHUB_REF_NAME
          path: Deploy/Windows
      - name: Upload Mac Artifact
        uses: actions/upload-artifact@v1
        with:
          name: OldImageFilterToolMac$GITHUB_REF_NAME
          path: Deploy/Mac
      - name: Create Release
        uses: Hs1r1us/Release-AIO@v1.0
        with:
          tag_name: $GITHUB_REF_NAME
          asset_files: Deploy
